theme: minima
title: No title
author: Merilin Ali
email: merilinayhan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello! I'm Merilin.

# social links
twitter_username: merilinali # DO NOT include the @ character, or else the build will fail!
github_username:  merilinali # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
